name = "FunctionIndices"
uuid = "43668171-7344-4272-8ca6-106380bd294d"
authors = ["Long Wang <wangl.cc@outlook.com>"]
version = "0.3.0-DEV"

[deps]
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"

[compat]
MappedArrays = "0.3, 0.4"
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
